/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeItemFinderRouteImport } from './routes/home-item-finder'
import { Route as IndexRouteImport } from './routes/index'

const HomeItemFinderRoute = HomeItemFinderRouteImport.update({
  id: '/home-item-finder',
  path: '/home-item-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home-item-finder': typeof HomeItemFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home-item-finder': typeof HomeItemFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home-item-finder': typeof HomeItemFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home-item-finder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home-item-finder'
  id: '__root__' | '/' | '/home-item-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeItemFinderRoute: typeof HomeItemFinderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home-item-finder': {
      id: '/home-item-finder'
      path: '/home-item-finder'
      fullPath: '/home-item-finder'
      preLoaderRoute: typeof HomeItemFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeItemFinderRoute: HomeItemFinderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
